modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="goodblock"
version="1.0.0"
displayName="goodblock-1.20.1"
credits="逸云 , 缘来007 ,Goodtimes2,"
displayURL="https://github.com/hhdsjgit/Good-blocks"
logoFile="logo.png"
authors="Goodtimes2"
description='''
Some of the content additions to Changed addon plus
'''

[[dependencies.goodblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.goodblock]]
    modId="changed"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


