modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="goodblock"
version="0.7.2"
displayName="goodblock"
credits="逸云 , 缘来007 ,好好的时间2"
displayURL="https://github.com/hhdsjgit/Good-blocks"
logoFile="logo.png"
authors="好好的时间2"
description='''
Some of the content additions to Changed addon plus
'''

[[dependencies.goodblock]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.goodblock]]
    modId="changed_addon"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.goodblock]]
    modId="changed"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


